services:
  mongodb:
    image: mongo:4.4.29
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS:-pass}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS:-pass}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ADMIN_USER:-admin}:${MONGO_ADMIN_PASS:-pass}@mongodb:27017
    depends_on:
      - "mongodb"

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
      args:
        BUILD_MODE: prod
    restart: always
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb://${MONGO_ADMIN_USER:-admin}:${MONGO_ADMIN_PASS:-pass}@mongodb:27017
      - URI=https://matatak.org
      - ALLOWED_ORIGINS=https://matatak.org,https://www.matatak.org
      - PROD=true
    depends_on:
      - "mongodb"
